name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: To reproduce
      description: Steps to reproduce the behaviour.
      placeholder: How to reproduce!
      value: "Steps to reproduce the behaviour."
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots"
      description: If applicable, add screenshots to help explain your problem.
      value: |
        ![DESCRIPTION](LINK.png)
      render: bash
    validations:
      required: false
  - type: textarea
    id: expectation
    attributes:
      label: Expected Behaviour
      description: Expected behaviour.
      placeholder: What is expected behaviour!
      value: "A clear and concise description of what you expected to happen."
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      placeholder: Release version AASX Server V3 2023-11-17.alpha
    validations:
      required: false
  - type: input
    id: OS
    attributes:
      label: Operating System
      description: Operating System
      placeholder: Windows, Linux
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. 
      render: shell
